# Generated by Django 3.0.1 on 2020-01-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190714_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
