# Generated by Django 3.0.1 on 2020-01-19 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20200119_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=120)),
                ('amount', models.BigIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
