# Generated by Django 3.0.1 on 2020-01-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='factory',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
